name: Build app for release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter with FVM
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Enable macOS
        run: flutter config --enable-macos-desktop

      - name: Build macOS app
        run: flutter build macos

      - name: Zip macOS app
        run: |
          cd build/macos/Build/Products/Release
          zip -r app-macos.zip *.app

      - name: Upload build to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/macos/Build/Products/Release/app-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
